import traceback
import sys
from traceback_example import produce_exception